<h1>Combining football-data and making changes to the data

In [1]:
import constants as c
import pandas as pd

In [2]:
# Load the CSV files
df1 = pd.read_csv(c.fb_data_18_19)
df2 = pd.read_csv(c.fb_data_19_20)
df3 = pd.read_csv(c.fb_data_20_21)
df4 = pd.read_csv(c.fb_data_21_22)
df5 = pd.read_csv(c.fb_data_22_23)

# Combine all the dataframes
combined_df = pd.concat([df1, df2, df3, df4, df5], ignore_index=True)

# Rename columns
combined_df.rename(columns={'HomeTeam': 'Home_Team', 'AwayTeam': 'Away_Team'}, inplace=True)

# Define reverse mapping dictionary from df
team_mapping = {
    'Crystal Palace': 'Crystal Palace',
    'Chelsea': 'Chelsea',
    'Man United': 'Manchester Utd',
    'Arsenal': 'Arsenal',
    'Southampton': 'Southampton',
    'Everton': 'Everton',
    'Leicester': 'Leicester City',
    'Aston Villa': 'Aston Villa',
    'Leeds': 'Leeds United',
    'Brentford': 'Brentford',
    'Brighton': 'Brighton',
    'Newcastle': 'Newcastle Utd',
    'West Ham': 'West Ham',
    'Man City': 'Manchester City',
    'Tottenham': 'Tottenham',
    'Liverpool': 'Liverpool',
    'Fulham': 'Fulham',
    'Bournemouth': 'Bournemouth',
    'Wolves': 'Wolves',
    "Nott'm Forest": "Nott'ham Forest",
    'Norwich': 'Norwich City',
    'Burnley': 'Burnley',
    'Watford': 'Watford',
    'Sheffield United': 'Sheffield Utd',
    'West Brom': 'West Brom',
    'Huddersfield': 'Huddersfield',
    'Cardiff': 'Cardiff City'
}

# Map values in combined_df using the mapping dictionary
combined_df['Home_Team'] = combined_df['Home_Team'].map(team_mapping)
combined_df['Away_Team'] = combined_df['Away_Team'].map(team_mapping)


# Save the combined dataframe to a new CSV file
combined_df.to_csv(c.combined_df_filepath, index=False)

combined_df.head(5)

,Div,Date,Home_Team,Away_Team,FTHG,FTAG,FTR,HTHG,HTAG,HTR,...,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
0,E0,10-08-2018,Manchester Utd,Leicester City,2,1,H,1,0,H,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,E0,11-08-2018,Bournemouth,Cardiff City,2,0,H,1,0,H,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,E0,11-08-2018,Fulham,Crystal Palace,0,2,A,0,1,A,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,E0,11-08-2018,Huddersfield,Chelsea,0,3,A,0,2,A,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,E0,11-08-2018,Newcastle Utd,Tottenham,1,2,A,1,2,A,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

<h1>Combining Kaggle and Football-data

In [3]:
import pandas as pd

# Read files into pandas dataframes
file1_df = pd.read_csv(c.combined_df_filepath, encoding ='latin')
file2_df = pd.read_csv(c.EPL_2018_2023, encoding='latin')

# Merge dataframes based on Date, Home_Team, and Away_Team
merged_df = pd.merge(file2_df, file1_df[['Season','Home_Team', 'Away_Team', 'B365H', 'B365D', 'B365A']], 
                    on=['Season','Home_Team', 'Away_Team'], how='left')

# Write merged dataframe back to file2
merged_df.to_csv(c.final_data, index=False)
merged_df

,Week,Date,Time,Home_Team,Home_xG,Score,Away_xG,Away_Team,Attendance,Venue,Referee,Season,B365H,B365D,B365A
0,38,28-05-2023,16:30,Crystal Palace,1.4,1Â—1,0.5,Nott'ham Forest,25198.0,Selhurst Park,Thomas Bramall,2022-2023,1.67,4.00,5.00
1,38,28-05-2023,16:30,Chelsea,2.2,1Â—1,1.7,Newcastle Utd,40130.0,Stamford Bridge,Jarred Gillett,2022-2023,2.90,3.50,2.38
2,38,28-05-2023,16:30,Manchester Utd,2.9,2Â—1,1.8,Fulham,73465.0,Old Trafford,Robert Jones,2022-2023,1.50,4.33,6.00
3,38,28-05-2023,16:30,Arsenal,2.8,5Â—0,0.5,Wolves,60095.0,Emirates Stadium,Andre Marriner,2022-2023,1.36,5.25,8.00
4,38,28-05-2023,16:30,Southampton,1.8,4Â—4,4.0,Liverpool,31129.0,St. Mary's Stadium,Darren England,2022-2023,6.50,4.75,1.44
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1895,1,11-08-2018,15:00,Bournemouth,2.2,2Â—0,1.4,Cardiff City,10353.0,Vitality Stadium,Kevin Friend,2018-2019,1.90,3.60,4.50
1896,1,11-08-2018,15:00,Watford,1.2,2Â—0,0.3,Brighton,20051.0,Vicarage Road Stadium,Jonathan Moss,2018-2019,2.37,3.20,3.40
1897,1,11-08-2018,15:00,Huddersfield,0.3,0Â—3,1.9,Chelsea,24121.0,The John Smith's Stadium,Chris Kavanagh,2018-2019,6.50,4.00,1.61
1898,1,11-08-2018,17:30,Wolves,1.0,2Â—2,1.0,Everton,31231.0,Molineux Stadium,Craig Pawson,2018-2019,2.37,3.30,3.30
1899,1,10-08-2018,20:00,Manchester Utd,1.5,2Â—1,1.8,Leicester City,74439.0,Old Trafford,Andre Marriner,2018-2019,1.57,3.90,7.50

<h1>All Kaggle data combined

In [ ]:
import pandas as pd
df = pd.read_csv(c.EPL_2018_2023, encoding='latin')
df.head(5)